source "https://rubygems.org"

# Specify your gem's dependencies in interscript.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"

gem "interscript-maps", path: "../maps"

gem 'simplecov', require: false, group: :test