source "https://rubygems.org"

# Specify your gem's dependencies in interscript.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"

gem "interscript-maps", path: "../maps"

if File.exist? "../../secryst"
  gem "secryst", path: "../../secryst"
else
  gem "secryst"
end

gem 'regexp_parser'

gem 'mini_racer'

gem 'simplecov', require: false, group: :test
