name: rake

on:
  push:
    branches: [ main, v*, ci-check ]
    tags: [ v* ]
  pull_request:

jobs:
  rspec:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "3.0", 2.7, 2.6 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - ruby: "3.1"
            os: 'ubuntu-latest'
          - ruby: "3.2"
            os: 'ubuntu-latest'
          - ruby: "3.1"
            os: 'macos-latest'
          - ruby: "3.2"
            os: 'macos-latest'

    env:
      BUNDLE_WITHOUT: "secryst"
      SKIP_JS: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: interscript/interscript

      - name: Run bootstrap script
        run: ruby bootstrap.rb

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpecs
        working-directory: ./ruby
        run: |
          bundle install --with=jsexec
          bundle exec rspec -f f
