name: rake

on:
  push:
    branches: [ main, v*, ci-check ]
    tags: [ v* ]
  pull_request:

jobs:
  rspec:
    name: Test on Ruby ${{ matrix.ruby }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3", "3.4"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      BUNDLE_WITHOUT: "secryst"
      SKIP_JS: "1"

    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v7
        with:
          repository: interscript/interscript

      - name: Bootstrap packages
        run: ruby bootstrap.rb

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ruby

      - name: Install Python helper and gems
        working-directory: ruby
        run: |
          pip install regex
          bundle config set --local with jsexec
          bundle install

      - name: RSpec
        working-directory: ruby
        run: bundle exec rspec

  standard:
    name: StandardRB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - run: bundle exec standardrb
