name: rake

on:
  push:
    branches: [ master, v* ]
    tags: [ v* ]
  pull_request:

jobs:
  rspec:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.7, 2.6, 2.5 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]
        include:
          - ruby: 3.0
            os: 'ubuntu-latest'
            experimental: true
          - ruby: 3.0
            os: 'windows-latest'
            experimental: true
          - ruby: 3.0
            os: 'macos-latest'
            experimental: true

    env:
      BUNDLE_WITHOUT: "secryst"
      SKIP_JS: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: interscript/interscript-bootstrap

      - name: Run a bootstrap script
        run: env; ruby bootstrap.rb

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ./ruby

      - name: Run RSpecs
        run: |
          pushd ruby
          bundle install --with=jsexec
          bundle exec rspec -f f
          popd
