name: release

permissions:
  contents: write
  packages: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch or pre|rc|etc
        required: true
        default: "skip"
  repository_dispatch:
    types: [do-release]

jobs:
  release:
    uses: metanorma/ci/.github/workflows/rubygems-release.yml@main
    with:
      next_version: ${{ github.event.inputs.next_version }}
    secrets:
      rubygems-api-key: ${{ secrets.INTERSCRIPT_RUBYGEMS_API_KEY }}
      pat_token: ${{ secrets.GITHUB_TOKEN }}
