name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v7
        with:
          repository: interscript/interscript

      - name: Bootstrap packages
        run: ruby bootstrap.rb

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: ruby

      - uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: js/package-lock.json

      - name: Install gems
        working-directory: ruby
        run: bundle install --jobs 4 --retry 3 --with jsexec --without secryst

      - name: Test Ruby package
        working-directory: ruby
        run: bundle exec rake

      - name: Test JS package
        working-directory: js
        run: npm install && npm run prepareMaps && npm test

      - name: Publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{ secrets.INTERSCRIPT_RUBYGEMS_API_KEY }}
        working-directory: ruby
        run: |
          mkdir -p ~/.gem
          printf -- "---\n:rubygems_api_key: %s\n" "$RUBYGEMS_API_KEY" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem install gem-release
          gem release
